steps:
  # Clone the private GitHub repository using the GitHub access token variable
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone --recursive https://github.com/Antony-2504/Node.js-Application-Code.git source
  # Copy the build artifact to your VM instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'scp'
      - '--recurse'
      - 'source'
      - 'suhailakofficial@first:/home/'
      - '--zone=us-central1-a'
